### ISSUE TITLE
How can I get robot's ground truth pose from webots?

### ISSUE THREAD

**Issue by bigbigpark** [cyberbotics/webots_ros2#464]
I have successfully built and run [webots_ros2](https://github.com/cyberbotics/webots_ros2).

When I type this command,`ros2 launch webots_ros2_mavic robot_launch.py`
![image](https://user-images.githubusercontent.com/72936863/188086002-37164fa3-e50d-4669-a552-a1170eac2085.png)

It worked well.
Now I want to get **Ground Truth Pose** of the Quadrotor as a format of 9-DoF.
I know the position(x, y, z) is got from GPS sensor and the linear acceleration & angular velocity from Inertial Measurement Units.

To see what's topic is streaming, `ros2 topic list`,
![image](https://user-images.githubusercontent.com/72936863/188086471-56584f9b-f2b6-4be3-bd3c-dfe4f2db4688.png)

It gives me a correct GPS data, but cannot offer **linear_acceleration**..
How can I get this?

I mean when I type `ros2 topic echo /imu`, they print 
![image](https://user-images.githubusercontent.com/72936863/188086897-dff26c75-e0aa-48d2-948b-f8985c27ac4a.png)

**Comment by omichel** [comment]
This is likely due to the fact that the [Mavic2](https://github.com/cyberbotics/webots/blob/71c53a91fab8eab737495c9471b11634d177f781/projects/robots/dji/mavic/protos/Mavic2Pro.proto#L61-L68) robot misses an [Accelerometer](https://www.cyberbotics.com/doc/reference/accelerometer) node. It has a [Compass](https://www.cyberbotics.com/doc/reference/compass), [Gyro](https://www.cyberbotics.com/doc/reference/gyro), [InertialUnit](https://www.cyberbotics.com/doc/reference/inertialunit) (providing only yaw, pitch, roll) and GPS. Adding an Accelerometer to the PROTO file should resolve the issue.

**Comment by bigbigpark** [comment]
@omichel 
Thanks for replying.
I'm pretty new about webots. Could you give me some guidance?

**Comment by omichel** [comment]
I would recommend you to follow this tutorial: https://docs.ros.org/en/galactic/Tutorials/Advanced/Simulators/Webots.html
