### ISSUE TITLE
Improper conversion to rclpy.Time for nanoseconds 

### ISSUE THREAD

**Issue by 3wnbr1** [cyberbotics/webots_ros2#71]
In `webots_node`, time is converted from unix timestamp format to `rclpy.Time`

https://github.com/cyberbotics/webots_ros2/blob/40385d93f49812357145cb9b285758b8fcbcbf55/webots_ros2_core/webots_ros2_core/webots_node.py#L93

However, there seems to be an error in the conversion as stated nanoseconds are in fact microseconds. Therefore, the line should be :

```python
nanoseconds = int((sim_time - seconds) * 1e9)
```

**Comment by DavidMansolino** [comment]
You are completely right! We are going to fix this soon.

**Comment by lukicdarkoo** [comment]
@3wnbr1 Thank you for reporting the issue!

We have decided to delete `now()` method in favor of [`self.get_clock().now().to_msg()`]( http://docs.ros2.org/eloquent/api/rclpy/api/node.html?highlight=get_clock#rclpy.node.Node.get_clock). It is ROS2 way of dealing with time:
- if `--ros-args --param use_sim_time:=true` is used, your node will use simulated time,
- otherwise it will automatically switch to real-time.

If you exclusively want to use the simulated time you can use:
```
Time(seconds=self.robot.getTime()).to_msg()
```
